"""study_plan_generated_at_onupdate

Revision ID: 031ee54f680b
Revises: ee5264c5e019
Create Date: 2026-05-29 06:18:34.995181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031ee54f680b'
down_revision: Union[str, None] = 'ee5264c5e019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
