"""add_vocab_tables

Revision ID: 4dda205240cc
Revises: 5f97f8229cae
Create Date: 2026-05-29 06:55:02.154924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dda205240cc'
down_revision: Union[str, None] = '5f97f8229cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_vocabulary',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'word', name='uq_student_vocabulary')
    )
    op.create_index(op.f('ix_student_vocabulary_student_id'), 'student_vocabulary', ['student_id'], unique=False)
    op.create_table('word_unlocks',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('introduced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_unlocks_session_id'), 'word_unlocks', ['session_id'], unique=False)
    op.create_index(op.f('ix_word_unlocks_student_id'), 'word_unlocks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_unlocks_student_id'), table_name='word_unlocks')
    op.drop_index(op.f('ix_word_unlocks_session_id'), table_name='word_unlocks')
    op.drop_table('word_unlocks')
    op.drop_index(op.f('ix_student_vocabulary_student_id'), table_name='student_vocabulary')
    op.drop_table('student_vocabulary')
    # ### end Alembic commands ###
