"""add_grammar_tables

Revision ID: 5f97f8229cae
Revises: ee972d4d6d16
Create Date: 2026-05-29 06:44:12.188457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f97f8229cae'
down_revision: Union[str, None] = 'ee972d4d6d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_exercises',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('question_json', sa.JSON(), nullable=False),
    sa.Column('answered_correctly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_exercises_student_id'), 'grammar_exercises', ['student_id'], unique=False)
    op.create_table('student_grammar_weaknesses',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'category', name='uq_student_grammar_category')
    )
    op.create_index(op.f('ix_student_grammar_weaknesses_student_id'), 'student_grammar_weaknesses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_grammar_weaknesses_student_id'), table_name='student_grammar_weaknesses')
    op.drop_table('student_grammar_weaknesses')
    op.drop_index(op.f('ix_grammar_exercises_student_id'), table_name='grammar_exercises')
    op.drop_table('grammar_exercises')
    # ### end Alembic commands ###
