"""add_lesson_stage_columns

Revision ID: aaa41ea09e9f
Revises: e897985e0486
Create Date: 2026-05-29 07:08:27.060604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa41ea09e9f'
down_revision: Union[str, None] = 'e897985e0486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('stage_content', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('current_stage', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'current_stage')
    op.drop_column('classes', 'stage_content')
    # ### end Alembic commands ###
