"""add_student_memories

Revision ID: de3ebc977bd9
Revises: 031ee54f680b
Create Date: 2026-05-29 06:31:22.976040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3ebc977bd9'
down_revision: Union[str, None] = '031ee54f680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_memories',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('memory_value', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('source_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'memory_type', 'memory_value', name='uq_student_memory')
    )
    op.create_index(op.f('ix_student_memories_student_id'), 'student_memories', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_memories_student_id'), table_name='student_memories')
    op.drop_table('student_memories')
    # ### end Alembic commands ###
