"""add_learning_tables

Revision ID: ee5264c5e019
Revises: f9e680a5420e
Create Date: 2026-05-29 05:59:11.792991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5264c5e019'
down_revision: Union[str, None] = 'f9e680a5420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_learning_profiles',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fluency_band', sa.Float(), nullable=True),
    sa.Column('grammar_band', sa.Float(), nullable=True),
    sa.Column('vocabulary_band', sa.Float(), nullable=True),
    sa.Column('overall_band', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('mistake_frequencies', sa.JSON(), nullable=True),
    sa.Column('vocab_mastery', sa.JSON(), nullable=True),
    sa.Column('sessions_analyzed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_learning_profiles_student_id'), 'student_learning_profiles', ['student_id'], unique=True)
    op.create_table('analysis_results',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('grammar_mistakes', sa.JSON(), nullable=True),
    sa.Column('vocab_usage', sa.JSON(), nullable=True),
    sa.Column('fluency_metrics', sa.JSON(), nullable=True),
    sa.Column('band_estimate', sa.JSON(), nullable=True),
    sa.Column('raw_nova_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_session_id'), 'analysis_results', ['session_id'], unique=True)
    op.create_index(op.f('ix_analysis_results_student_id'), 'analysis_results', ['student_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('source_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('generated_plan', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_analysis_results_student_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_session_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_student_learning_profiles_student_id'), table_name='student_learning_profiles')
    op.drop_table('student_learning_profiles')
    # ### end Alembic commands ###
